import { StyleSheet, Platform } from "react-native";

const createStyles = (theme) => {
  const { spacing, typography, colors: COLORS } = theme;

  const isWeb = Platform.OS === "web";
  const isNativeMobile = Platform.OS === "ios" || Platform.OS === "android";

  return StyleSheet.create({
    listActionsMenu: {
      marginLeft: 8,
      position: "relative",
      zIndex: 20,
    },
    sidebarItemContent: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      flex: 1,
      gap: 8,
    },
    sidebarItemLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 0,
      flex: 1,
      minWidth: 0,
    },
    sidebarItemAction: {
      marginLeft: 4,
    },

    listTextInputField: {
      borderWidth: 1,
      borderColor: COLORS.border,
      borderRadius: 10,
      backgroundColor: COLORS.input,
      paddingHorizontal: 12,
      height: 44,
      justifyContent: "center",
    },
    listTextInput: {
      color: COLORS.foreground,
      fontSize: 14,
    },
    navHelperText: {
      color: COLORS.mutedForeground,
      fontSize: 12,
      paddingHorizontal: 12,
      marginTop: 8,
    },
    bookmarkToolbar: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      flexWrap: "wrap",
    },
    secondarySearchContainer: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "transparent",
      borderWidth: 1,
      borderColor: COLORS.border,
      borderRadius: 8,
      paddingHorizontal: 10,
      height: 38,
      flexGrow: 1,
      maxWidth: 300,
    },
    bookmarkSearchInput: {
      flex: 1,
      fontSize: 13,
      marginLeft: 8,
      color: COLORS.foreground,
      outlineStyle: "none",
    },
    searchClearBtn: {
      marginLeft: 6,
      padding: 4,
    },
    emptyStateContainer: {
      alignItems: "center",
      justifyContent: "center",
      padding: spacing.xxl,
      borderWidth: 1,
      borderColor: COLORS.border,
      borderRadius: 12,
      backgroundColor: COLORS.card,
      minHeight: 300,
      marginBottom: 100,
    },
    emptyStateTitle: {
      fontSize: typography.lg,
      fontWeight: typography.weightBold,
      color: COLORS.foreground,
      marginBottom: spacing.xs,
      textAlign: "center",
    },
    emptyStateSubtext: {
      fontSize: typography.sm,
      color: COLORS.foreground,
      textAlign: "center",
      opacity: 0.7,
    },
    bookmarkButton: {
      height: 40,
      width: 40,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: COLORS.border,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: COLORS.card,
    },
    bookmarkButtonActive: {
      borderColor: COLORS.primary,
    },
    rightSidebar: {
      width: 340,
      minHeight: 320,
      padding: 20,
      borderWidth: 1,
      borderColor: COLORS.border,
      borderRadius: 15,
    },
    webContainer: {
      flex: 1,
      flexDirection: "row",
      backgroundColor: COLORS.background,
      maxWidth: 1440,
      width: "100%",
      alignSelf: "center",
      height: "100vh",
      overflow: "hidden",
    },
    sidebar: {
      width: 260,
      borderRightWidth: 1,
      borderRightColor: COLORS.border,
      paddingVertical: 24,
      paddingHorizontal: 10,
      backgroundColor: COLORS.sidebar,
      justifyContent: "space-between",
      display: "flex",
      flexDirection: "column",
    },
    sidebarFooter: {
      paddingTop: 16,
      borderTopWidth: 1,
      borderTopColor: COLORS.border,
    },
    logoContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 0,
    },
    logoImage: {
      width: 180,
      height: 60,
    },
    logoImageSmall: {
      width: 45,
      height: 45,
    },
    navGroup: {
      marginBottom: 32,
    },
    navHeader: {
      fontSize: 11,
      fontWeight: "600",
      color: COLORS.mutedForeground,
      marginBottom: 12,
      paddingHorizontal: 12,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      opacity: 0.5,
    },
    sidebarContent: {
      flex: 1,
      minHeight: 0,
    },
    sidebarScroll: {
      paddingTop: 40,
      flex: 1,
      minHeight: 0,
    },
    sidebarScrollContent: {
      paddingBottom: 16,
    },
    sidebarItem: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 6,
      marginBottom: 4,
      position: "relative",
      overflow: "visible",
      ...Platform.select({
        web: { transition: "all 0.2s ease" },
      }),
    },
    abstractContainer: {
      overflow: "hidden",
    },
    abstractMeasurements: {
      position: "absolute",
      opacity: 0,
      left: 0,
      right: 0,
      top: 0,
      zIndex: -1,
    },
    abstractMeasurementText: {
      includeFontPadding: false,
    },
    sidebarTooltip: {
      position: Platform.select({ web: "fixed", default: "absolute" }),
      left: "100%",
      top: "50%",
      marginLeft: 0,
      paddingHorizontal: 10,
      paddingVertical: 6,
      backgroundColor: COLORS.foreground,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: COLORS.border,
      zIndex: 2000,
      maxWidth: 360,
      transform: [{ translateY: -18 }],
      ...Platform.select({
        web: {
          whiteSpace: "nowrap",
          width: "max-content",
          maxWidth: 480,
        },
      }),
    },
    sidebarTooltipText: {
      color: COLORS.background,
      fontSize: 12,
      fontWeight: "500",
    },
    sidebarItemActive: {
      backgroundColor: COLORS.sidebarActive,
    },
    sidebarItemHover: {
      backgroundColor: COLORS.generalHover,
    },
    sidebarText: {
      fontSize: 14,
      color: COLORS.mutedForeground,
      fontWeight: "500",
      flex: 1,
    },
    sidebarTextActive: {
      color: COLORS.foreground,
      fontWeight: "500",
    },
    mobileMenuOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 200,
      elevation: 200, // For Android
    },
    mobileMenuBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "rgba(0,0,0,0.5)",
    },
    mobileMenuDrawer: {
      position: "absolute",
      padding: 15,
      top: 0,
      bottom: 0,
      right: 0,
      width: "80%", // Drawer width
      maxWidth: 300,
      backgroundColor: COLORS.background,
      borderRightWidth: 1,
      borderRightColor: COLORS.border,
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowOpacity: 0.25,
      shadowRadius: 10,
      elevation: 10,
      zIndex: 201,
      display: "flex",
      flexDirection: "column",
    },
    mobileMenuContainer: {
      flex: 1,
      flexDirection: "column",
      justifyContent: "space-between",
    },
    mobileMenuHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      alignSelf: "flex-end",
      marginBottom: 10,
      paddingTop: 50,
    },
    mobileHeader: {
      height: 56,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      borderBottomWidth: 1,
      borderBottomColor: COLORS.border,
      backgroundColor: COLORS.background,
      zIndex: 50,
    },
    logoRow: {
      flexDirection: "row",
      alignItems: "center",
    },
    desktopHeader: {
      height: 72,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 48,
      borderBottomWidth: 1,
      borderBottomColor: COLORS.border,
      backgroundColor: COLORS.background,
      backdropFilter: "blur(8px)",
    },
    searchContainer: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: COLORS.input,
      borderWidth: 1,
      borderColor: COLORS.border,
      borderRadius: 8,
      paddingHorizontal: 10,
      height: 36,
      width: 320,
    },
    searchContainerMobile: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: COLORS.input,
      borderRadius: 8,
      paddingHorizontal: 12,
      height: 48,
      width: "100%",
    },
    headerInput: {
      flex: 1,
      fontSize: 14,
      marginLeft: 8,
      color: COLORS.foreground,
      outlineStyle: "none",
    },
    advancedIconBtn: {
      marginLeft: 8,
      padding: 4,
    },
    scrollContent: {
      paddingHorizontal: 48,
      paddingTop: 48,
    },
    scrollContentMobile: {
      paddingHorizontal: 20,
      paddingTop: 24,
    },
    hero: {
      marginBottom: 40,
      maxWidth: 700,
    },
    heroTitle: {
      fontSize: 48,
      fontWeight: "800",
      color: COLORS.foreground,
      letterSpacing: -1.5,
      lineHeight: 52,
      marginBottom: 16,
    },
    heroTitleMobile: {
      fontSize: 34,
      lineHeight: 40,
      letterSpacing: -1,
    },
    heroSubtitle: {
      fontSize: 18,
      color: COLORS.mutedForeground,
      lineHeight: 28,
    },
    tabsSection: {
      flexDirection: "column",
      justifyContent: "space-between",
      marginBottom: 15,
      backgroundColor: COLORS.background,
      paddingVertical: 10,
      zIndex: 10,
    },
    tabsSectionMobile: {
      flexDirection: "column",
      alignItems: "flex-start",
      width: "100%",
    },
    activeFilterPill: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: COLORS.secondary,
      borderWidth: 1,
      borderColor: COLORS.border,
      borderRadius: 8,
      paddingLeft: 12,
      paddingRight: 8,
      height: 38,
      gap: 8,
      flexShrink: 1,
      maxWidth: "100%",
    },
    activeFilterText: {
      fontSize: 13,
      color: COLORS.foreground,
      fontWeight: "600",
      flexShrink: 1,
    },
    activeFilterIconBox: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: "rgba(255,255,255,0.1)",
      justifyContent: "center",
      alignItems: "center",
      flexShrink: 0,
    },
    gridDesktop: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 32,
    },
    gridMobile: {
      flexDirection: "column",
      gap: 24,
    },
    errorContainer: {
      alignItems: "center",
      justifyContent: "center",
      padding: 40,
    },
    errorText: {
      fontSize: 18,
      fontWeight: "600",
      color: COLORS.foreground,
    },
    errorSubtext: {
      fontSize: 14,
      color: COLORS.mutedForeground,
      marginTop: 8,
      textAlign: "center",
    },
    paperCard: {
      backgroundColor: COLORS.card,
      borderWidth: 1,
      borderColor: COLORS.border,
      borderRadius: 16,
      padding: 24,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.0,
      shadowRadius: 8,
      display: "flex",
      flexDirection: "column",
      zIndex: 1,
      ...Platform.select({
        web: { transition: "all 0.2s ease" },
      }),
    },
    cardTopRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
      zIndex: 10,
    },
    tagRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
    },
    cardHeader: {
      marginBottom: 12,
      zIndex: 1,
    },
    paperTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: COLORS.foreground,
      marginBottom: 8,
      lineHeight: 26,
      letterSpacing: -0.25,
    },
    paperTitleMobile: {
      fontSize: 21,
      lineHeight: 28,
    },
    paperMeta: {
      fontSize: 14,
      color: COLORS.mutedForeground,
      fontWeight: "500",
    },
    cardContent: {
      flex: 1,
      marginBottom: 24,
      zIndex: 1,
    },
    paperAbstract: {
      fontSize: 15,
      color: "#a1a1aa",
      lineHeight: 24,
    },
    cardFooter: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingTop: 20,
      borderTopWidth: 1,
      borderTopColor: COLORS.border,
      zIndex: 1,
    },
    metaStat: {
      flexDirection: "row",
      alignItems: "center",
    },

    readContainer: {
      flex: 1,
      backgroundColor: COLORS.background,
      position: "relative",
    },
    contentArea: {
      flex: 1,
      backgroundColor: "#1c1c1e",
    },
    pdfContainer: {
      flex: 1,
      backgroundColor: "#1c1c1e",
      overflow: "hidden",
    },
    overlayControls: {
      position: "absolute",
      bottom: 40,
      left: 20,
      right: 20,
      flexDirection: "row",
      justifyContent: "space-between",
      zIndex: 100,
    },
    inReaderButton: {
      flexDirection: "row",
      gap: 5,
      height: 40,
      borderRadius: 20,
      backgroundColor: "rgba(39, 39, 42, 0.8)",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.1)",
      ...Platform.select({
        web: { cursor: "pointer", transition: "all 0.2s ease" },
      }),
    },
    loadingOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: COLORS.background,
      justifyContent: "center",
      alignItems: "center",
    },
    badge: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 6,
      borderWidth: 1,
    },
    badgeText: {
      fontSize: 12,
      fontWeight: "600",
    },
    popoverWrapper: {
      position: "absolute",
      top: 60,
      zIndex: 999,
    },
    popoverBackdrop: {
      ...Platform.select({
        web: {
          position: "fixed",
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          width: "100vw",
          height: "100vh",
          cursor: "default",
        },
        native: {
          position: "absolute",
          top: -1000,
          left: -1000,
          right: -1000,
          bottom: -1000,
        },
      }),
      zIndex: 998,
    },
    popoverContainer: {
      width: 180,
      backgroundColor: COLORS.background,
      borderWidth: 1,
      borderColor: COLORS.border,
      borderRadius: 12,
      padding: 8,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.05,
      shadowRadius: 7,
      zIndex: 999,
    },
    popoverHeader: {
      fontSize: 11,
      fontWeight: "600",
      color: COLORS.mutedForeground,
      marginBottom: 6,
      paddingHorizontal: 8,
      marginTop: 4,
      textTransform: "uppercase",
    },
    popoverItem: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 10,
      paddingHorizontal: 8,
      borderRadius: 6,
      ...Platform.select({
        web: { cursor: "pointer", transition: "all 0.1s ease" },
      }),
    },
    popoverItemHover: {
      backgroundColor: COLORS.generalHover,
    },
    popoverItemText: {
      fontSize: 13,
      color: COLORS.mutedForeground,
      fontWeight: "500",
    },
    popoverItemTextActive: {
      color: COLORS.foreground,
      fontWeight: "600",
    },

    modalOverlay: {
      flex: 1,
      // backgroundColor: "rgba(0,0,0,0.7)",
      justifyContent: "flex-end",
    },

    modalOverlayCentered: {
      justifyContent: "center",
      alignItems: "center",
      padding: isNativeMobile ? 0 : 16,
    },
    modalOverlayFullScreen: {
      justifyContent: "flex-start",
      alignItems: "stretch",
      padding: 0,
    },
    modalSurface: {
      backgroundColor: COLORS.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: COLORS.border,
      padding: 24,
      gap: 12,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.18,
      shadowRadius: 18,
    },
    modalSurfaceMedium: {
      width: isWeb ? 560 : "100%",
    },
    modalSurfaceWide: {
      width: isWeb ? 780 : "100%",
      maxHeight: isNativeMobile ? "100%" : "82%",
      minHeight: 0,
      overflow: "hidden",
    },
    modalSurfaceNarrow: {
      width: isWeb ? 460 : "100%",
    },
    modalSurfaceFullScreen: {
      width: "100%",
      height: "100%",
      maxHeight: "100%",
      borderRadius: 16,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "600",
      color: COLORS.foreground,
    },
    modalSubtitle: {
      fontSize: 14,
      color: COLORS.mutedForeground,
      marginTop: 4,
    },
    inputGroup: {
      padding: 5,
      marginBottom: 5,
    },
    inputLabel: {
      fontSize: 13,
      fontWeight: "500",
      color: COLORS.foreground,
      marginBottom: 8,
    },
    modalFooter: {
      flexDirection: "row",
      justifyContent: "center",
      marginTop: 24,
      paddingTop: 16,
    },
    headerActions: {
      flexDirection: "row",
      alignItems: "center",
      gap: 0,
    },
    authSummaryCard: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: COLORS.secondary,
      padding: 12,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: COLORS.border,
    },
    authLabel: {
      fontSize: 12,
      color: COLORS.mutedForeground,
    },
    authEmail: {
      fontSize: 14,
      fontWeight: "600",
      color: COLORS.foreground,
    },

    modalBackdropTransparent: {
      flex: 1,
      backgroundColor: "transparent",
    },

    modalHeaderRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      marginBottom: 12,
    },
    authActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 12,
      marginTop: 8,
    },
    authErrorText: {
      color: COLORS.destructive,
      fontSize: 13,
      marginTop: -2,
    },
    avatarButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: COLORS.foreground,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: COLORS.border,
      ...Platform.select({
        web: { cursor: "pointer" },
      }),
    },
    avatarText: {
      fontSize: 16,
      fontWeight: "600",
      color: COLORS.background,
    },
    forgotPasswordText: {
      fontSize: 12,
      color: COLORS.mutedForeground,
      fontWeight: "500",
      textDecorationLine: "underline",
    },
    modalCard: {
      backgroundColor: COLORS.card,
      borderRadius: 16,
      padding: 30,
      width: isWeb ? 700 : "100%",
      maxHeight: isNativeMobile ? "100%" : "80%",
      borderWidth: 1,
      borderColor: COLORS.border,
      gap: 12,
    },
    modalCardFullScreen: {
      width: "100%",
      height: "100%",
      maxHeight: "100%",
      borderRadius: 16,
    },
    detailSection: {
      marginBottom: 14,
    },
    detailLabel: {
      fontSize: 12,
      color: COLORS.mutedForeground,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      marginBottom: 6,
    },
    detailValue: {
      fontSize: 14,
      color: COLORS.foreground,
      lineHeight: 20,
    },
    modalTagRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
    },
    modalTag: {
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    linkList: {
      gap: 8,
    },
    linkPill: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 8,
      paddingHorizontal: 10,
      borderWidth: 1,
      borderColor: COLORS.border,
      borderRadius: 10,
      backgroundColor: COLORS.input,
    },
    linkText: {
      color: COLORS.primary,
      fontWeight: "600",
    },

    listModalBody: {
      flexGrow: 1,
      minHeight: 0,
      flexShrink: 1,
      width: "100%",
    },
    listModalActionsContainer: {
      width: "100%",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 5,
      marginTop: 8,
    },
    listModalActions: {
      marginTop: 0,
    },
    tagListScroll: {
      maxHeight: "78%",
    },
    tagSection: {
      marginBottom: 14,
      gap: 8,
    },
    tagSectionTitle: {
      fontSize: 14,
      color: COLORS.mutedForeground,
      fontWeight: "700",
      letterSpacing: 0.2,
      textTransform: "uppercase",
    },
    tagList: {
      flexDirection: "row",
      flexWrap: "wrap",
      rowGap: 8,
      columnGap: 8,
    },
    tagRowItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingVertical: 8,
      paddingHorizontal: 14,
      backgroundColor: COLORS.secondary,
      borderWidth: 1,
      borderColor: COLORS.border,
      borderRadius: 9999,
      alignSelf: "flex-start",
      ...Platform.select({
        web: { cursor: "pointer", transition: "all 0.15s ease" },
      }),
    },
    tagRowItemHover: {
      backgroundColor: COLORS.generalHover,
    },
    tagCodePill: {
      paddingVertical: 4,
      paddingHorizontal: 10,
      backgroundColor: COLORS.card,
      borderRadius: 9999,
      borderWidth: 1,
      borderColor: COLORS.border,
    },
    tagCode: {
      fontSize: 12,
      fontWeight: "700",
      color: COLORS.foreground,
      letterSpacing: 0.3,
      textTransform: "uppercase",
    },
    tagName: {
      fontSize: 14,
      color: COLORS.foreground,
      flexShrink: 1,
      fontWeight: "500",
    },

    tagSectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    tagSectionHeaderContent: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    inReaderButtonActive: {
      backgroundColor: "rgba(255,255,255,0.8)",
      borderColor: "rgba(0,0,0,0.1)",
    },
    bookmarkErrorBanner: {
      position: "absolute",
      bottom: 72,
      right: 16,
      left: 16,
      borderRadius: 12,
      padding: 10,
      backgroundColor: COLORS.card,
      borderWidth: 1,
      borderColor: COLORS.border,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    bookmarkErrorText: {
      color: "red",
      fontSize: 12,
      flex: 1,
    },
    seeMoreButton: {
      position: "absolute",
      bottom: 30,
      width: 300,
      alignSelf: "center",
    },
    comboboxContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "center",
      gap: 6,
      padding: 8,
      borderWidth: 1,
      borderColor: COLORS.border,
      borderRadius: 8,
      backgroundColor: COLORS.input,
      minHeight: 42,
    },
    comboboxPill: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: COLORS.secondary,
      borderRadius: 4,
      paddingVertical: 2,
      paddingHorizontal: 8,
      borderWidth: 1,
      borderColor: COLORS.border,
    },
    comboboxPillText: {
      fontSize: 12,
      fontWeight: "500",
      color: COLORS.foreground,
      marginRight: 4,
    },
    comboboxInput: {
      flex: 1,
      minWidth: 80, // ensures input is clickable even when row is full
      fontSize: 14,
      color: COLORS.foreground,
      paddingVertical: 2,
      paddingHorizontal: 4,
      height: 24,
    },

    suggestionListContainer: {
      flex: 1,
      marginTop: 8,
      borderWidth: 1,
      borderColor: COLORS.border,
      borderRadius: 8,
      backgroundColor: COLORS.card,
      overflow: "hidden",
    },
    noResultsText: {
      padding: 16,
      fontSize: 13,
      color: COLORS.mutedForeground,
      textAlign: "center",
      fontStyle: "italic",
    },
    listTextInputField: {
      borderRadius: 10,
    },
    listTextInput: {
      color: COLORS.foreground,
      fontSize: 14,
      borderWidth: 1,
      borderColor: COLORS.border,
      borderRadius: 8,
      paddingHorizontal: 12,
      height: 40,
      backgroundColor: theme.colorScheme === "dark" ? COLORS.input : "#ffffff",
      // removes the ugly blue focus outline on Web
      ...Platform.select({
        web: { outlineStyle: "none" },
      }),
    },

    comboboxContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "center",
      gap: 6,
      padding: 8,
      borderWidth: 1,
      borderColor: COLORS.border,
      borderRadius: 8,
      backgroundColor: theme.colorScheme === "dark" ? COLORS.input : "#ffffff",
      minHeight: 42,
    },
    comboboxPill: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: COLORS.primary,
      borderRadius: 4,
      paddingVertical: 4,
      paddingHorizontal: 8,
    },
    comboboxPillText: {
      fontSize: 12,
      fontWeight: "600",
      color: COLORS.primaryForeground,
      marginRight: 4,
    },
    comboboxInput: {
      flex: 1,
      minWidth: 80,
      fontSize: 14,
      color: COLORS.foreground,
      paddingVertical: 2,
      paddingHorizontal: 4,
      height: 24,
      // removes the ugly blue focus outline on Web
      ...Platform.select({
        web: { outlineStyle: "none" },
      }),
    },
    suggestionListContainer: {
      flex: 1,
      marginTop: 8,
      borderWidth: 1,
      borderColor: COLORS.border,
      borderRadius: 8,
      backgroundColor: COLORS.card,
      overflow: "hidden",
    },
    suggestionGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      padding: 12,
      gap: 8,
    },
    suggestionBadge: {
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: COLORS.border,
      backgroundColor: COLORS.secondary,
    },
    suggestionBadgeText: {
      fontSize: 13,
      fontWeight: "500",
      color: COLORS.foreground,
    },
    noResultsText: {
      padding: 16,
      fontSize: 13,
      color: COLORS.mutedForeground,
      textAlign: "center",
      fontStyle: "italic",
      width: "100%",
    },
    modalCard: {
      backgroundColor: COLORS.card,
      borderRadius: 12,
      width: isWeb ? 600 : "94%",
      maxHeight: "85%",
      borderWidth: 1,
      borderColor: COLORS.border,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      display: "flex",
      flexDirection: "column",
      overflow: "hidden",
      minHeight: 0,
      alignSelf: "center",
    },
    modalHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 24,
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: COLORS.border,
      backgroundColor: COLORS.card,
    },
    modalHeaderLabel: {
      fontSize: 14,
      fontWeight: "600",
      color: COLORS.foreground,
    },

    modalHeroTitle: {
      fontSize: 22,
      fontWeight: "700",
      color: COLORS.foreground,
      lineHeight: 28,
      marginTop: 24,
      marginBottom: 12,
      letterSpacing: -0.5,
    },
    modalTagRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
    },

    metaGrid: {
      gap: 16,
    },
    metaRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 12,
    },
    metaLabel: {
      fontSize: 12,
      fontWeight: "500",
      color: COLORS.mutedForeground,
      marginBottom: 2,
    },
    metaValue: {
      fontSize: 14,
      color: COLORS.foreground,
      lineHeight: 20,
    },

    separator: {
      height: 1,
      backgroundColor: COLORS.border,
      marginVertical: 24,
    },
    sectionHeader: {
      fontSize: 16,
      fontWeight: "600",
      color: COLORS.foreground,
      marginBottom: 8,
      letterSpacing: -0.3,
    },
    abstractText: {
      fontSize: 15,
      color: COLORS.mutedForeground,
      lineHeight: 24,
    },
    commentText: {
      fontSize: 14,
      color: COLORS.mutedForeground,
      fontStyle: "italic",
      backgroundColor: COLORS.secondary,
      padding: 12,
      borderRadius: 8,
      overflow: "hidden",
    },

    linkListContainer: {
      borderWidth: 1,
      borderColor: COLORS.border,
      borderRadius: 8,
      overflow: "hidden",
    },
    linkRowItem: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      padding: 12,
      backgroundColor: COLORS.card,
    },
    linkRowItemBorder: {
      borderBottomWidth: 1,
      borderBottomColor: COLORS.border,
    },
    linkIconBox: {
      width: 28,
      height: 28,
      borderRadius: 6,
      backgroundColor: COLORS.secondary,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: COLORS.border,
    },
    linkRowText: {
      fontSize: 14,
      fontWeight: "500",
      color: COLORS.foreground,
    },
    linkText: {
      color: COLORS.primary,
      textDecorationLine: "underline",
    },

    passwordToggle: {
      position: "absolute",
      right: 12,
      top: 10,
      height: 24,
      justifyContent: "center",
      alignItems: "center",
    },
    passwordInput: {
      paddingRight: 36,
    },
    authCardShell: {
      width: isWeb ? 420 : "100%",
      backgroundColor: COLORS.background,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: COLORS.border,
      padding: 22,
      gap: 0,
      shadowColor: "#000",
      shadowOpacity: 0.08,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      ...Platform.select({
        web: { boxShadow: `0px 20px 45px ${COLORS.shadow}` },
      }),
    },
    authCardContent: {
      gap: 18,
    },
    authCardHeaderCenter: {
      gap: 6,
    },
    authHeroTitle: {
      fontSize: 21,
      fontWeight: "600",
      color: COLORS.foreground,
    },
    authHeroSubtitle: {
      fontSize: 14,
      color: COLORS.mutedForeground,
      lineHeight: 20,
    },
    authFormStack: {
      gap: 16,
    },
    authFieldBlock: {
      gap: 8,
    },
    authLabelRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    authLabelText: {
      fontSize: 13,
      fontWeight: "600",
      color: COLORS.foreground,
    },
    authInputSpacing: {
      marginBottom: 0,
    },
    authPasswordInputWrapper: {
      position: "relative",
    },
    authInlineLinkText: {
      fontSize: 12,
      color: COLORS.primary,
      fontWeight: "600",
      textDecorationLine: "underline",
    },
    authActionsStack: {
      gap: 12,
      marginTop: 8,
    },
    authPrimaryButton: {
      width: "100%",
      height: 46,
    },
    authSwitchRow: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: 4,
    },
    authSwitchPrompt: {
      fontSize: 13,
      color: COLORS.mutedForeground,
    },
  });
};

export default createStyles;
